#!/bin/sh
#PBS -N PU_CNN
#PBS -q serial
#PBS -P CSCI1166
#PBS -l place=free
#PBS -l select=1:ncpus=8:mem=32gb
#PBS -l walltime=05:30:00
#PBS -m abe -M u12201732@tuks.co.za
#PBS -o /home/smanganye/lustre/stdoutput.out
#PBS -e /home/smanganye/lustre/stderror.err

source /etc/profile.d/modules.sh
ulimit -s unlimited
echo 'Run Starting'

cd /home/smanganye/lustre/Convolutional-Neural-Networks


module load chpc/python/anaconda/3-2021.11
source myenv/bin/activate

python run.py
