#!/bin/sh
#PBS -N PU_CNN_SMP
#PBS -q smp
#PBS -P CSCI1166
#PBS -l place=free
#PBS -l select=1:ncpus=24:mem=61gb
#PBS -l walltime=96:00:00
#PBS -m abe -M u12201732@tuks.co.za
#PBS -o /home/smanganye/lustre/stdoutput_M6_SMP.out
#PBS -e /home/smanganye/lustre/stderror_M6_SMP.err

source /etc/profile.d/modules.sh
ulimit -s unlimited
echo 'Run Starting'

cd /home/smanganye/lustre/PU_CNN_CIFAR_100


module load chpc/python/anaconda/3-2021.11
source myenv/bin/activate

python run.py model_6.yaml


